---
title: "homework2"
author: "Yihao Song(Allen)"
date: "2017
output:
  html_document: default
  word_document: default
---

```{r}
# 1st question, if we want to achieve 0.8 power, how many samples do we need
power <- 0.8
alpha <- 0.05
z0 <- qnorm(p = 0.975)
z1 <- qnorm(p = 0.2)
n <- 2 * (z0 - z1) ^ 2
n
```

```{r}
# relations between sample size N with delta(effect size)
N <- NULL
Del <- NULL
for(del in c(1:1000)){
  Del <- c(Del,del)
  N <- c(N, (2 * (z0 - z1)^2 / del ^ 2))
}
plot(x = log(Del), y = N)
```

```{r}
# relations between sample size N with variance
Var_a <- NULL
N <- NULL
for(var in c(1:1000)){
  Var_a <- c(Var_a, var)
  N <- c(N, ((2 * var) * (z0 - z1)^2))
}
plot(x = Var_a, y = N)
```


```{r}
# rolling dice
# using chi square test to test if they are fair dices
# test goodness of fitting
p1 <- 1/6
p0 <- 5/6
chisq.test(x = c(48,35,15,3),
           p = c(
                p0 ^ 3, 
                choose(3,1) * p1 * (p0 ^ 2),
                choose(3,2) * (p1 ^ 2) * p0,
                p1 ^ 3
                )
           )
```

